title:        ConFlo
tagline:      'ConFlo, let the conversations flow.'
description:  'A GPT-3 powered conversation moderator'
url:          www.philhosophist.com
version:      0.0.0
author:
  name:       ''
  email:      ''
markdown:     kramdown
permalink:    pretty
pygments:     true
paginate:     5
plugins: [jekyll-paginate]